device: 'cuda'
checkpoint_load:
checkpoint_save:
log:
data_root: 'data/'

dataset: 'cifar100'
num_classes: 
input_height: 
input_width:
input_channel:

epochs: 2
batch_size: 128
num_workers: 4
lr: 0.01
lr_scheduler: CosineAnnealingLR
pin_memory: True
non_blocking: True
prefetch: False
client_optimizer: sgd
sgd_momentum: 0.9
wd: 0.0005

poison_rate: 0.1
target_type: 'all2one'
target_label: 0

model: 'preactresnet18'
random_seed: 0
index: 

ratio: 0.05
clean_ratio: 0.2
poison_ratio: 0.05
