_BASE_: "../base-prompt.yaml"
RUN_N_TIMES: 1
DATA:
  NAME: "OxfordFlowers"
  DATAPATH: "/data/yangsheng/badvpt/vpt-main/datasets/oxfordflowers"  #TODO: need to specify here
  NUMBER_CLASSES: 102
  MULTILABEL: False
MODEL:
  TYPE: "vit"
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001