attack_label_trans: all2one
attack_target: 0

attack: blind

weight_loss_balance_mode: fixed
mgda_normalize: loss+
fix_scale_normal_weight: 1.0
fix_scale_backdoor_weight: 0.9
batch_history_len: 1000
backdoor_batch_loss_threshold: 1.0