device: 'cuda'
amp: True
pin_memory: True
non_blocking: True
prefetch: False

checkpoint_load:
checkpoint_save:
log:
dataset_path: './data'
dataset: 'gtsrb'

epochs: 100
batch_size: 256
num_workers: 4
lr: 0.01
lr_scheduler: CosineAnnealingLR
model: 'preactresnet18'

client_optimizer: 'sgd'
sgd_momentum: 0.9 
wd: 5.0e-4
frequency_save: 0

random_seed: 0

index: 
te_epochs: 10
momentum: 0.9
weight_decay: 1.0e-4
ratio: 0.05
beta1: 500
beta2: 1000
beta3: 1000
p: 2.0

teacher_model_loc: 



