---
seed:
  seed: 100
  deterministic: False
  benchmark: True
dataset_dir: ~/dataset/vggface2_30/train
num_classes: 30
saved_dir: ./saved_data
storage_dir: ./storage
prefetch: True
transform:
  pre:
    resize:
      size: 256
    center_crop:
      size: 224
  aug:
    primary:
      random_resize_crop:
        size: 224
        scale: [0.2, 1.0]
        interpolation: 3  # BICUBIC
      random_horizontal_flip:
        p: 0.5
      random_color_jitter:
        p: 0.8
        brightness: 0.4
        contrast: 0.4
        saturation: 0.4
        hue: 0.1
      random_grayscale: 
        p: 0.2
      gaussian_blur:
        p: 0.5
        sigma: [0.1, 2.0]
    remaining:
      to_tensor: True
      normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
  train:
    primary:
      random_resize_crop:
        size: 224
        scale: [0.2, 1.0]
        interpolation: 3  # BICUBIC
      random_horizontal_flip:
        p: 0.5
    remaining:
      to_tensor: True
      normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
  test:
    primary: null
    remaining:
      to_tensor: True
      normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
backdoor:
  poison_ratio: 0.05
  target_label: 3
  blend:
    alpha: 0.1
    trigger_path: ./data/trigger/noise.png
loader:
  batch_size: 512
  num_workers: 0
  pin_memory: True
network:
  densenet121_face:
    num_classes: 30
sync_bn: True
criterion:
  simclr:
    temperature: 0.5
optimizer:
  SGD:
    weight_decay: 1.e-4
    momentum: 0.9
    lr: 0.4
lr_scheduler:
  cosine_annealing:
    T_max: 1000  # same as `num_epochs`
num_epochs: 1000